# Generated by Django 5.0.2 on 2024-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.FloatField()),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ml_app_stockdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.IntegerField(default=0)),
                ('dividends', models.FloatField(default=0.0)),
                ('stock_splits', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MLAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
