# Generated by Django 4.2.9 on 2024-01-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.FloatField()),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
    ]
