# Generated by Django 5.0.1 on 2024-01-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_alter_stockdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
