# Generated by Django 5.0.1 on 2024-01-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0003_mlaccuracy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'managed': False},
        ),
    ]
