# Generated by Django 5.0.1 on 2024-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_alter_stockdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_field', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelTable(
            name='stockdata',
            table='ml_app_stockdata',
        ),
    ]
