# Generated by Django 5.0.1 on 2024-02-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_inputdata_alter_stockdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='input_field',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='dividends',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='stock_splits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
